import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from './components/Nav'
import {getServerSession} from 'next-auth/next'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  //fetch user
  const session = await getServerSession(authOptions)
  console.log('====================================');
  console.log(session);
  console.log('====================================');
  return (
    <html lang="en">
      <body className="mx-64">
        <Nav expires={''} user={session?.user}/>
        {children}
        </body>
    </html>
  )
}
